export const DOGS_LOADING = 'DOGS_LOADING';
export const ADD_DOGS = 'ADD_DOGS';
export const DOGS_FAILED = 'DOGS_FAILED';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const PARTNERS_LOADING = 'PARTNERS_LOADING';
export const ADD_PARTNERS = 'ADD_PARTNERS';
export const PARTNERS_FAILED = 'PARTNERS_FAILED';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';

export const ADD_COMMENT = 'ADD_COMMENT';